### ISSUE TITLE
Thrive's Roadmap

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/thrive#1]
This issue contains the current roadmap for Thrive. Thanks to anyone who helps out by flagging issues or contributing code 🙌🏽.

- **Navigation**
  - [ ] Up (`..`): Moves up tree
  - [ ] Back (`<`): Previous location
  - [ ] Forward (`>`): Forward location
- **Files**
  - [ ] Create file (`<path>`): Create file
  - [ ] Open file (`<path>`): Open file
  - [ ] Delete file (`<path> del`): Delete file
  - [ ] Examine file (`<path> exm`): View file properties
- **Directories**
  - [ ] Create directory (`<path>`): Create directory
  - [ ] Open directory (`<path>`): Open directory
  - [ ] List directory (`<path> ls`): List directory contents
  - [ ] Delete directory (`<path> del`): Delete directory (recursive)
  - [ ] Examine directory (`<path> exm`): View directory properties
- **Other**
  - [ ] REPL (`repl`): Open REPL session
  - [ ] Exec (`<path> exec`): Execute `.thrive` file
